---

#kvm if config
net_if:
   - eno1
   - eno2

# vlan's number match to bridges and bonds in netplan and bridges names in virsh net-list 
vlan:
   - 441
   - 442
   - 443
   - 444
   - 445
   - 446
   - 491
   - 492
   - 493
   - 494
   - 496
   - 698
   - 829
   - 838
   - 839
   - 852

# network settings
host_ip_mask: 10.4.90.5/24
gw_ip: 10.4.90.1
dns_ip:
   - 10.4.92.23
   - 10.4.92.25
search_domain: cpci.1cupis.org

#virsh pool config
virt_pool:
   - name: "lvm"
     pool: "vg"
     dev: "/dev/vg"
     type: "logical"

   - name: "ssd"
     pool: "ssd"
     dev: "/dev/ssd"
     type: "logical"

   - name: "ssd_k"
     pool: "ssd_k"
     dev: "/dev/ssd_k"
     type: "logical"

   - name: "nvram"
     pool: "nvram"
     dev: "/var/lib/libvirt/qemu/nvram"
     type: "dir"
